$(info Reading ex-contents.mk $(COMPONENT_DIR))

VPATH += $(COMPONENT_DIR) $(COMPONENT_DIR)/../mod1 $(COMPONENT_DIR)/../mod2

OFLUX_PROJECT_NAME:=plugin3
OFLUX_PLUGIN_PROJECTS+= $(OFLUX_PROJECT_NAME)
OFLUX_TESTS+=$(OFLUX_PROJECT_NAME)_done

$(OFLUX_PROJECT_NAME)_FROM_PROJECT:=kernalex
$(OFLUX_PROJECT_NAME)_DEP_PLUGINS:=plugin1

######################################################################################################

$(OFLUX_PROJECT_NAME)_OFLUX_SRC:=mImpl_$(OFLUX_PROJECT_NAME).cpp mImpl_$($(OFLUX_PROJECT_NAME)_FROM_PROJECT)_mod1.cpp mImpl_$($(OFLUX_PROJECT_NAME)_FROM_PROJECT)_mod2.cpp

$(OFLUX_PROJECT_NAME)_OFLUX_PATH:=$(COMPONENT_DIR)
$(OFLUX_PROJECT_NAME)_OFLUX_INCS:=-I $($(OFLUX_PROJECT_NAME)_OFLUX_PATH) -I $(COMPONENT_DIR)/../mod1 -I $(COMPONENT_DIR)/../mod2

$(OFLUX_PROJECT_NAME)_OFLUX_INCLUDES:=

$(OFLUX_PROJECT_NAME)_OFLUX_MODULES:= mod1.flux mod2.flux

$(OFLUX_PROJECT_NAME)_OFLUX_MAIN:=$(OFLUX_PROJECT_NAME).flux

$(OFLUX_PROJECT_NAME)_OFLUX_CXXFLAGS:=
$(OFLUX_PROJECT_NAME)_OFLUX_OPTS:= -x
