$(info Reading ex-contents.mk $(COMPONENT_DIR))


OFLUX_PROJECT_NAME:=timer1


OFLUX_PROJECTS+= $(OFLUX_PROJECT_NAME)

OFLUX_TESTS+= run-$(OFLUX_PROJECT_NAME).sh

$(OFLUX_PROJECT_NAME)_OFLUX_MODULES:= Timer.flux

$(OFLUX_PROJECT_NAME)_OFLUX_MAIN:=$(OFLUX_PROJECT_NAME).flux

$(OFLUX_PROJECT_NAME)_OFLUX_SRC:= \
	mImpl_$(OFLUX_PROJECT_NAME).cpp \
	mImpl_$(OFLUX_PROJECT_NAME)_Timer.cpp \
	TimerInterface.cpp

$(OFLUX_PROJECT_NAME)_OFLUX_CXXFLAGS:= -DTESTING -DHASINIT



$(OFLUX_PROJECT_NAME)_OFLUX_PATH:=$(COMPONENT_DIR)
$(OFLUX_PROJECT_NAME)_OFLUX_INCS:= \
	-I $($(OFLUX_PROJECT_NAME)_OFLUX_PATH)

$(OFLUX_PROJECT_NAME)_OFLUX_INCLUDES:= 


