
OFLUX_PROJECTS+= $(OFLUX_PROJECT_NAME)
OFLUX_TESTS+= $(OFLUX_PROJECT_NAME)_load_test

$(OFLUX_PROJECT_NAME)_OFLUX_MODULES:=

$(OFLUX_PROJECT_NAME)_OFLUX_MAIN:=$(OFLUX_PROJECT_NAME).flux

$(OFLUX_PROJECT_NAME)_OFLUX_SRC:=mImpl_$(OFLUX_PROJECT_NAME).cpp
$(OFLUX_PROJECT_NAME)_OFLUX_CXXFLAGS:= -DTESTING

############################################################################
## General stuff for build tests


$(OFLUX_PROJECT_NAME)_OFLUX_PATH:=$(COMPONENT_DIR)
$(OFLUX_PROJECT_NAME)_OFLUX_INCS:=-I $($(OFLUX_PROJECT_NAME)_OFLUX_PATH)
$(OFLUX_PROJECT_NAME)_OFLUX_OPTS:=

$(OFLUX_PROJECT_NAME)_OFLUX_INCLUDES:=
$(OFLUX_PROJECT_NAME)_OFLUX_KERNEL:=


