$(info Reading ex-contents.mk $(COMPONENT_DIR))

VPATH+= \
	$(COMPONENT_DIR)/AMod \
	$(COMPONENT_DIR)/BMod \
	$(COMPONENT_DIR)/CMod

OFLUX_PROJECT_NAME:=moduse


OFLUX_PROJECTS+= $(OFLUX_PROJECT_NAME)
OFLUX_TESTS+= run-$(OFLUX_PROJECT_NAME).sh

$(OFLUX_PROJECT_NAME)_OFLUX_MODULES:= AMod.flux BMod.flux CMod.flux

$(OFLUX_PROJECT_NAME)_OFLUX_MAIN:=$(OFLUX_PROJECT_NAME).flux

$(OFLUX_PROJECT_NAME)_OFLUX_SRC:= \
	mImpl_$(OFLUX_PROJECT_NAME).cpp \
	mImpl_$(OFLUX_PROJECT_NAME)_AMod.cpp \
	mImpl_$(OFLUX_PROJECT_NAME)_BMod.cpp \
	mImpl_$(OFLUX_PROJECT_NAME)_CMod.cpp

$(OFLUX_PROJECT_NAME)_OFLUX_CXXFLAGS:= -DTESTING


$(OFLUX_PROJECT_NAME)_OFLUX_PATH:=$(COMPONENT_DIR)
$(OFLUX_PROJECT_NAME)_OFLUX_INCS:= \
	-I $($(OFLUX_PROJECT_NAME)_OFLUX_PATH) \
	-I $(COMPONENT_DIR)/AMod \
	-I $(COMPONENT_DIR)/BMod \
	-I $(COMPONENT_DIR)/CMod

$(OFLUX_PROJECT_NAME)_OFLUX_INCLUDES:= 


