$(info Reading ex-contents.mk $(COMPONENT_DIR))

OFLUX_PROJECT_NAME:=plugin1
OFLUX_PLUGIN_PROJECTS+= $(OFLUX_PROJECT_NAME)
OFLUX_TESTS+=$(OFLUX_PROJECT_NAME)_done

$(OFLUX_PROJECT_NAME)_FROM_PROJECT:=kernalex
$(OFLUX_PROJECT_NAME)_DEP_PLUGINS:=

######################################################################################################

$(OFLUX_PROJECT_NAME)_OFLUX_SRC:=mImpl_$(OFLUX_PROJECT_NAME).cpp

$(OFLUX_PROJECT_NAME)_OFLUX_PATH:=$(COMPONENT_DIR)
$(OFLUX_PROJECT_NAME)_OFLUX_INCS:=-I $($(OFLUX_PROJECT_NAME)_OFLUX_PATH)

$(OFLUX_PROJECT_NAME)_OFLUX_INCLUDES:=

$(OFLUX_PROJECT_NAME)_OFLUX_MODULES:= 

$(OFLUX_PROJECT_NAME)_OFLUX_MAIN:=$(OFLUX_PROJECT_NAME).flux

$(OFLUX_PROJECT_NAME)_OFLUX_CXXFLAGS:=
$(OFLUX_PROJECT_NAME)_OFLUX_OPTS:= -x
